version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch-2
    restart: no
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9201:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  
  redis:
    image: redis:7.2
    container_name: redis-2
    restart: no
    ports:
      - "6278:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--appendonly", "yes"]

  postgres:
    image: postgres:16-alpine
    container_name: postgres-2
    restart: no
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
      POSTGRES_DB: ${PG_DATABASE:-franchiso}
    ports:
      - "5433:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: franchiso-app
    restart: no
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./uploads:/root/uploads
    env_file:
      - .env
    environment:
      ELASTIC_URL: http://elasticsearch:9200
      PG_ADDR: postgres:5432
      PG_USER: ${PG_USER:-postgres}
      PG_PASSWORD: ${PG_PASSWORD:-postgres}
      PG_DATABASE: ${PG_DATABASE:-franchiso}
      REDIS_ADDR: redis:6379
      MIDTRANS_SERVER_KEY: ${MIDTRANS_SERVER_KEY}
      MIDTRANS_ENV: ${MIDTRANS_ENV}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_ACTIVE: ${GEMINI_ACTIVE}
      SMTP_ACC: ${SMTP_ACC}
      SMTP_ACC_PASSWORD: ${SMTP_ACC_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      elasticsearch:
        condition: service_started

  ai_module:
    image: ai_module
    build:
      context: ./ai_module
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: no
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      elasticsearch:
        condition: service_started

volumes:
  esdata:
  redisdata:
  postgresdata:
